version: "3.8"

services:
  books-db:
    image: postgres:16.4
    container_name: books-db-container
    restart: always
    environment:
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books-net

  books-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: books-backend
    ports:
      - "8080:8080"
    depends_on:
      - books-db
    links:
      - books-db
    networks:
      - books-net

  books-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: books-frontend
    depends_on:
      - books-backend
    links:
      - books-backend
    ports:
      - "5173:5173"
    networks:
      - books-net
  cypress:
    image: cypress/included:12.5.1
    depends_on:
      - books-frontend
      - books-backend
    environment:
      - CYPRESS_BASE_URL=http://books-frontend:5173
    working_dir: /e2e
    volumes:
      - ./frontend/cypress:/e2e
    networks:
      - books-net
    entrypoint: ["cypress", "run"]

networks:
  books-net:
    name: books-network
